version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    command: npm run dev

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    command: uvicorn inference.app:app --host 0.0.0.0 --port 8000

  airflow:
    image: apache/airflow:2.7.0
    ports:
      - "8080:8080"
    volumes:
      - ./backend/dags:/opt/airflow/dags
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
